version: '3'
services:
  kubectl-host:
    image: piotrzan/kubectl-comp:zsh
    container_name: kubectl-host
    tty: true
    network_mode: "host"
    volumes:
     - ~/.kube/:/root/.kube/
    entrypoint: "/bin/zsh"